spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/root
    username: root
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /studyit/api/v1
swagger.oauth.endpoint: http://localhost:8080/studyit/api/v1/users/token
password.token.live.time.hours: 48

