spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:localhost:3306/studyit_db1
    username: root
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /studyit/api/v1
swagger.oauth.endpoint: http://ec2-3-124-8-117.eu-central-1.compute.amazonaws.com/studyit/api/v1/users/token
password.token.live.time.hours: 48
authorization.server.signing.key: studyit
