spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /studyit/api/v1
